services:
  - type: web
    name: telehealth-app
    env: docker
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -c gunicorn_conf.py run:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: telehealthDB
          property: connectionString

databases:
  - name: telehealthDB
    databaseName: telehealthdb1
    user: kmchealth

