services:
  - type: web
    name: telehealth-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -c gunicorn_conf.py run:app"
    envVars:
      - key: FLASK_ENV
        value: production
