"""empty message

Revision ID: 0676780d05b4
Revises: e970505eb796
Create Date: 2025-05-27 19:27:57.121286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0676780d05b4'
down_revision = 'e970505eb796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
