"""empty message

Revision ID: 0781f2da3259
Revises: 48b7c94a74c2
Create Date: 2025-05-28 17:45:09.764667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0781f2da3259'
down_revision = '48b7c94a74c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
