"""unhashed dict

Revision ID: 0d3efa81bcbd
Revises: e68fff6549a8
Create Date: 2025-05-27 20:09:42.465465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3efa81bcbd'
down_revision = 'e68fff6549a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
