"""empty message

Revision ID: 151907a8780d
Revises: c31995463cbc
Create Date: 2025-04-18 09:19:19.751582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151907a8780d'
down_revision = 'c31995463cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_visit', sa.String(), nullable=False))
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('date_of_visit')

    # ### end Alembic commands ###
