"""empty message

Revision ID: 22891e88c81c
Revises: 0676780d05b4
Create Date: 2025-05-27 19:39:46.463770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22891e88c81c'
down_revision = '0676780d05b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
