"""empty message

Revision ID: 24e2eb806ba8
Revises: b9c8d98d19f8
Create Date: 2025-05-27 20:19:57.777651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e2eb806ba8'
down_revision = 'b9c8d98d19f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_constraint('FK__prescript__appoi__52E34C9D', type_='foreignkey')
        batch_op.create_foreign_key(None, 'appointments', ['appointment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__prescript__appoi__52E34C9D', 'prescriptions', ['appointment_id'], ['id'])

    # ### end Alembic commands ###
