"""empty message

Revision ID: 38b72cbd1468
Revises: 8d0d4224d283
Create Date: 2025-05-14 12:18:14.626177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b72cbd1468'
down_revision = '8d0d4224d283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
