"""prescriptions check

Revision ID: 3d7790e782bf
Revises: 38b72cbd1468
Create Date: 2025-05-14 12:46:07.158626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d7790e782bf'
down_revision = '38b72cbd1468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescription_status_change')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescription_status_change',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prescription_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('to_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('changed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name='prescription_status_change_changed_by_fkey'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name='prescription_status_change_prescription_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='prescription_status_change_pkey')
    )
    # ### end Alembic commands ###
