"""empty message

Revision ID: 48b7c94a74c2
Revises: 22891e88c81c
Create Date: 2025-05-28 17:34:56.087077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b7c94a74c2'
down_revision = '22891e88c81c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
