"""empty message

Revision ID: 8f1c7e827b14
Revises: f8d4f19a0b81
Create Date: 2025-05-28 19:06:56.764364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1c7e827b14'
down_revision = 'f8d4f19a0b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_appointments_doctor')
        batch_op.drop_constraint('FK__appointme__docto__756D6ECB', type_='foreignkey')
        batch_op.drop_column('doctor_id')

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_constraint('FK__medical_r__appoi__65F62111', type_='foreignkey')
        batch_op.drop_column('appointment_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_doctor')
        batch_op.drop_constraint('FK__payments__doctor__14E61A24', type_='foreignkey')
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('FK__payments__doctor__14E61A24', 'doctors', ['doctor_id'], ['id'])
        batch_op.create_index('ix_payments_doctor', ['doctor_id'], unique=False)

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('FK__medical_r__appoi__65F62111', 'appointments', ['appointment_id'], ['id'])

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('FK__appointme__docto__756D6ECB', 'doctors', ['doctor_id'], ['id'])
        batch_op.create_index('ix_appointments_doctor', ['doctor_id'], unique=False)

    # ### end Alembic commands ###
