"""empty message

Revision ID: b9c8d98d19f8
Revises: 75d087ae7cab
Create Date: 2025-05-27 20:09:45.334003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c8d98d19f8'
down_revision = '75d087ae7cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'prescriptions', ['appointment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('appointment_id')

    # ### end Alembic commands ###
