"""empty message

Revision ID: e68fff6549a8
Revises: e5090e66db0e
Create Date: 2025-05-27 19:59:53.734557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68fff6549a8'
down_revision = 'e5090e66db0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
