"""unhashed dict

Revision ID: e970505eb796
Revises: 0d3efa81bcbd
Create Date: 2025-05-27 20:19:50.276775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e970505eb796'
down_revision = '0d3efa81bcbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
