"""doctor profile

Revision ID: f7ca178dee33
Revises: fff6f8793394
Create Date: 2025-04-16 12:28:11.461225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ca178dee33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('schedule', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('schedule')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
