"""empty message

Revision ID: f8d4f19a0b81
Revises: 0781f2da3259
Create Date: 2025-05-28 18:06:55.852936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d4f19a0b81'
down_revision = '0781f2da3259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
